In [49]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms

import numpy as np

from collections import OrderedDict, defaultdict

In [67]:
class ClientDataset(Dataset):
    def __init__(self, img_tensors, lbl_tensors, transform=None):
        self.img_tensors = img_tensors
        self.lbl_tensors = lbl_tensors
        self.transform = transform
    
    def __len__(self):
        return self.lbl_tensors.shape[0]
    
    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
        return self.img_tensors[idx], self.lbl_tensors[idx]
    
def create_client_data_loaders(client_nums, data_folder, batch_size, random_mode=False):
    data_loaders = []
    for idx in range(client_nums):
        # loading data to tensors
        img_tensor_file = data_folder + f'client_{idx}_img.pt'
        lbl_tensor_file = data_folder + f'client_{idx}_lbl.pt'
        img_tensors = torch.load(img_tensor_file) # this contains 494 images, currently 76
        lbl_tensors = torch.load(lbl_tensor_file)

        # creating a dataset which can be fed to dataloader
        client_dataset = ClientDataset(img_tensors, lbl_tensors)
        data_loader = DataLoader(client_dataset, batch_size=batch_size, shuffle=random_mode)
        data_loaders.append(data_loader)
    return data_loaders

In [78]:
# Save the tensor of images and labels for clients
username = 'fnx11'
data_folder = f'/home/{username}/thesis/codes/Playground/data/fed_data/'
client_nums = 20
client_data_loaders = create_client_data_loaders(client_nums, data_folder, 8)

### Let's see some of the loaders

In [79]:
import matplotlib.pyplot as plt
%matplotlib inline

# helper function to un-normalize and display an image
def imshow(img):
    img = img / 2 + 0.5  # unnormalize
    plt.imshow(np.transpose(img, (1, 2, 0)))

def visualize(images, labels):
    images = images.numpy() # convert images to numpy for display
    # plot the images in the batch, along with the corresponding labels
    fig = plt.figure(figsize=(25, 4))
    # display 20 images
    for idx in np.arange(8):
        ax = fig.add_subplot(2, 8/2, idx+1, xticks=[], yticks=[])
        imshow(images[idx])
        ax.set_title(classes[labels[idx]])
    

In [84]:
client_iter = iter(client_data_loaders[15])
# specify the image classes
classes = ['airplane', 'automobile', 'bird', 'cat', 'deer',
           'dog', 'frog', 'horse', 'ship', 'truck']
for step in range(len(client_iter)):
    images, labels = next(client_iter)  
#     visualize(images, labels)
    print(images.shape)
    print(labels.shape)
    break

torch.Size([8, 3, 32, 32])
torch.Size([8])


In [1]:
from sklearn.cluster import KMeans
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4,5,80,90,100,110,120]).reshape(-1, 1)
arr2 = np.array([11,12,13,14,15,16,17,20,220,230]).reshape(-1, 1)
arr3 = np.array([100,120,105,8,9,10,11,12,13,14]).reshape(-1, 1)


In [7]:
kmeans1 = KMeans(n_clusters=2, random_state=0).fit(arr1)
centers1 = kmeans1.cluster_centers_
print(centers1)

kmeans2 = KMeans(n_clusters=2, random_state=0).fit(arr2)
centers2 = kmeans2.cluster_centers_
print(centers2)

kmeans3 = KMeans(n_clusters=2, random_state=0).fit(arr3)
centers3 = kmeans3.cluster_centers_
print(centers3)

[[100.]
 [  3.]]
[[ 14.75]
 [225.  ]]
[[ 11.        ]
 [108.33333333]]


In [8]:
mins = []

labels1 = kmeans1.predict(arr1)
val1, count1 = np.unique(labels1, return_counts=True)
print(count1)
mins.append(np.min(count1))

labels2 = kmeans2.predict(arr2)
val2, count2 = np.unique(labels2, return_counts=True)
print(count2)
mins.append(np.min(count2))

labels3 = kmeans3.predict(arr3)
val3, count3 = np.unique(labels3, return_counts=True)
print(count3)
mins.append(np.min(count3))

print(mins)

[5 5]
[8 2]
[7 3]
[5, 2, 3]


In [11]:
min_arr = np.array(mins).reshape(-1, 1)
kmeans = KMeans(n_clusters=2, random_state=0).fit(min_arr)
centers = kmeans.cluster_centers_
print(centers)

labels = kmeans.predict(min_arr)
print(labels)
val, count = np.unique(labels, return_counts=True)

[[5. ]
 [2.5]]
[0 1 1]


In [1]:
import numpy as np

In [2]:
arr = np.array([4,2,1,3,6,5])
brr = np.argsort(arr)[-3:]

In [3]:
print(arr)
print(brr)

[4 2 1 3 6 5]
[0 5 4]


In [4]:
arr[brr]

array([4, 5, 6])

In [5]:
len(arr)

6

In [6]:
arr.size

6

In [7]:
from sklearn.metrics.pairwise import cosine_similarity
arr1 = np.arange(10).reshape(1, -1)
arr2 = np.arange(10).reshape(1, -1)

print(cosine_similarity(arr1, arr2)[0][0])

0.9999999999999998


In [9]:
arr = arr.reshape(2,3)

In [10]:
arr

array([[4, 2, 1],
       [3, 6, 5]])

In [11]:
row_sum = arr.sum(axis=1)

In [12]:
print(row_sum)

[ 7 14]


In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [91]:
# assuming 10 clients and 8 itrs,
total_clients = 10
fdrs = 8
trust_scores = (np.random.random_sample((8, 10))*10000).astype(int)
initial_validation_clients = [1, 6]
poisoned_clients = [2,5,7]
start_cosdefence = 2

## client type means if client is honest(0), malicious(1), or initial validation client(-1)
# client_types = np.zeros((total_clients), dtype=int)
# client_types[initial_validation_clients] = -1
# client_types[poisoned_clients] = 1

client_types = ["honest" for _ in range(total_clients)]
print(client_types)
for val_client in initial_validation_clients:
    client_types[val_client] = "init_val"

for p_client in poisoned_clients:
    client_types[p_client] = "poisoned"
print(client_types)

['honest', 'honest', 'honest', 'honest', 'honest', 'honest', 'honest', 'honest', 'honest', 'honest']
['honest', 'init_val', 'poisoned', 'honest', 'honest', 'poisoned', 'init_val', 'poisoned', 'honest', 'honest']


In [89]:
trust_scores_df = pd.DataFrame(trust_scores, columns=[f"client{i}" for i in range(total_clients)])
trust_scores_df.head()

client0  client1  client2  client3  client4  client5  client6  client7  \
0     9559     8421     1387      563     5430     3867     2883     5711   
1     2398      890     6869     7202     6238     4633     6947     9017   
2     8858     4131     4728     8131     3941     3776     7622     3184   
3     4023     7808     9910     7249     8748     2232     6515     9999   
4     1383     4315     9361     6167     8774     3208      847     2043   

   client8  client9  
0     2097      623  
1     1616     7650  
2     6889     7366  
3     4426     9338  
4     6147     5281

In [90]:
import plotly.graph_objects as go

# Create random data with numpy

# Create traces
fig = go.Figure()
for i in range(total_clients):
    fig.add_trace(go.Scatter(x=list(range(start_cosdefence, fdrs)), y=trust_scores_df[f"client{i}"], mode='lines'))

fig.show()

In [93]:
trust_scores_df = pd.DataFrame(columns=["fed_round","trust_score", "client_id", "client_type"])
# [r for r in range(fdrs)], trust_scores[i], i, client_types[i]

for client in range(total_clients):
    temp_df = pd.DataFrame({"fed_round" : pd.Series(list(range(fdrs)), dtype="int"),
                            "trust_score" : trust_scores[:, client],
                            "client_id" : client,
                            "client_type":client_types[client]})
    trust_scores_df = trust_scores_df.append(temp_df, ignore_index=True)
print(trust_scores_df.shape)

(80, 4)


In [94]:
trust_scores_df.head()

fed_round trust_score client_id client_type
0         0        5349         0      honest
1         1        3991         0      honest
2         2        3904         0      honest
3         3        3805         0      honest
4         4        1422         0      honest

In [95]:
score_curves_fig = px.line(trust_scores_df, x="fed_round", y="trust_score", color="client_type",
              line_group="client_id", hover_name="client_id")
score_curves_fig.update_layout(title="Trust Score Evolution")
score_curves_fig.show()
#     score_curves_fig.write_html(os.path.join(save_location,'{}_trust_score_curves_{}.html'.format(config_details, time.strftime("%Y-%m-%d %H:%M:%S", current_time))))



In [82]:
df = px.data.gapminder().query("continent != 'Asia'") # remove Asia for visibility
fig = px.line(df, x="year", y="lifeExp", color="continent",
              line_group="country", hover_name="country")
fig.show()

(1704, 8)


In [96]:
from sklearn.cluster import KMeans
import numpy as np

comp_trusts = [1,2,3,40,50,60]
trust_arr = np.array(comp_trusts).reshape(-1, 1)
kmeans = KMeans(n_clusters=2, random_state=0).fit(trust_arr)

In [ ]:
.cluster_centers_